<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Jc_404 extends CI_Controller {

	/* 
		Description:
		This is for the Error 404 Page of Ynah's Thesis.
		The Error 404 page is generated by this controller.
		- Jc
	*/

	public function __construct(){
		parent::__construct();
	}

	public function index()
	{
		/*
		$this->output->set_status_header('404');
		$data['content'] = 'error_404';
		$this->load->view('index',$data);

		*/
	}

	
}
